---
- hosts: all
  tasks:
      - name: Install EPEL release for nginx
        yum: name=epel-release state=present

      - name: Install nginx web server
        yum: name=nginx state=installed update_cache=true
        notify:
          - start nginx

      - name: Upload the default index.html file
        copy: src=html_files/index.html dest=/usr/share/nginx/www/ mode=0644

  handlers:
      - name: start nginx
        service: name=nginx enables=yes state=started
